### ISSUE TITLE
Submit store to Stackage?

### ISSUE THREAD

**Issue by eschnett** [mgsloan/store#136]
I was trying to submit a package to Stackage https://github.com/commercialhaskell/stackage/pull/4061 , and this fails because its dependency `store` is not there. Could you add `store` to Stackage?

**Comment by snoyberg** [comment]
Feel free to continue on the master branch for now, I'm not actively doing anything on that branch for a while.

**Comment by mgsloan** [comment]
I've pushed a commit and uploaded version `0.5.0.1` which fixes compilation of the test-suite.  `stack init --resolver nightly` doesn't quite work, but it does build and pass tests with

```yaml
resolver: nightly-2018-10-20
packages:
- .
- store-core
- store-streaming
extra-deps:
- th-utilities-0.2.0.1@sha256:fbbb48b4e8d52153bda04f4e4e0c755506696125dee1f9278044e1c50b5eda7f
- cryptohash-0.11.9@sha256:59d9494ba0cc9eef087ecba2e12e4d3e2d3b0327dd1542af552e3dca0e7de70d
```
