### ISSUE TITLE
store-0.7.6 test suite fails to compile

### ISSUE THREAD

**Issue by DanBurton** [mgsloan/store#153]
I think it's due to a newer smallcheck than expected.

```
/Users/dan/scratch/store-0.7.6/test/Data/StoreSpec.hs:96:3: error:
    Duplicate instance declarations:
      instance Monad m => Serial m CBool
        -- Defined at test/Data/StoreSpec.hs:96:3
      instance [safe] Monad m => Serial m CBool
        -- Defined in ‘Test.SmallCheck.Series’
   |
96 | $(do let ns = [ ''CWchar, ''CUShort, ''CULong, ''CULLong, ''CIntMax
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

Etc for many similar errors.

I was able to reproduce this locally like so:

```bash
stack unpack store-0.7.6 && cd store-0.7.6
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: nightly-2020-08-27
extra-deps:
- store-core-0.4.4.3@sha256:50b3ef13ab5f82cccf665bd29edf37f69ef1e94c22802c2c94d0f74ce8808f09,1430
- th-utilities-0.2.4.0@sha256:ba19cd8441aa43dbaed40e9055bb5a7cbd7cf9e154f5253c6bf9293af8b1f96b,1869

```
